using UnityEngine;
using TMPro;
using UnityEngine.SceneManagement;

public class ControllerScene : MonoBehaviour
{
    
    public GameObject panelStart;
    public GameObject panelAbout;
    public TextMeshProUGUI aboutText; 

    public GameObject markPt;
    public GameObject markEn;

    void Start()
    {
        UpdateAboutText();
        UpdateLanguageMarkers();
    }
    
    public void UpdateAboutText()
    {
        // Cria o LanguageManager se não existir
        if (LanguageManager.Instance == null)
        {
            GameObject lmObject = new GameObject("LanguageManager");
            lmObject.AddComponent<LanguageManager>();
        }
        
        // Define o texto baseado no idioma
        string currentLanguage = LanguageManager.Instance.currentLanguage;
        
        if (currentLanguage == "pt")
        {
            // Texto em Português
            aboutText.text = "Sobre\n\n" +
                "Este projeto foi criado junto com meu filho.\n\n" +
                "Meu nome é Eduardo dos Santos, e trabalhei neste jogo ao lado de Eduardo dos Santos Jr. (11 anos). " +
                "Desenvolver este projeto juntos tem sido uma experiência muito especial para nós.\n\n" +
                "Sou desenvolvedor de software em uma grande multinacional brasileira, mas não trabalho profissionalmente com jogos. " +
                "Este jogo existe puramente por curiosidade, criatividade e o desejo de construir algo significativo juntos.\n\n" +
                "A data de envio, 28 de dezembro, também coincide com meu aniversário, o que torna este projeto ainda mais especial para mim. " +
                "Poder chegar a esta data tendo criado algo lado a lado com meu filho já é uma recompensa por si só.\n\n" +
                "Desenvolvimento & Game Jam\n\n" +
                "Este jogo foi desenvolvido para a Tiny Game Jam (12/25). " +
                "Começamos o projeto em 26 de dezembro, iniciando com o brainstorming da ideia central e criando os primeiros conceitos visuais.\n\n" +
                "O objetivo principal era manter o escopo pequeno e focado, enquanto experimentávamos com narrativa através de interpretação visual e contexto — " +
                "adequado ao espírito de uma game jam curta.\n\n" +
                "Notas Técnicas & Criativas\n\n" +
                "Engine: Unity\n\n" +
                "Assets: Alguns sprites e sons foram obtidos de recursos livres de direitos autorais.\n\n" +
                "Arte: Nem todas as imagens foram geradas por IA — vários desenhos e ideias vieram diretamente do meu filho.\n\n" +
                "Ferramentas de IA: Também usamos ferramentas de IA como Gemini (Nano Banana) e ChatGPT, principalmente para:\n\n" +
                "- Ajudar a traduzir a história e textos para inglês\n" +
                "- Auxiliar com conceitos e refinamento de imagens\n" +
                "- Melhorar clareza e consistência do conteúdo escrito\n\n" +
                "A IA foi usada como ferramenta de apoio, não como substituta da criatividade. " +
                "O projeto combina ideias humanas, aprendizado, experimentação e diversão.";
        }
        else
        {
            // Texto em Inglês (padrão)
            aboutText.text = "About\n\n" +
                "This project was created together with my son.\n\n" +
                "My name is Eduardo dos Santos, and I worked on this game alongside Eduardo dos Santos Jr. (11 years old). " +
                "Developing this project together has been a very special experience for us.\n\n" +
                "I am a software developer at a large Brazilian multinational company, but I do not work professionally with games. " +
                "This game exists purely because of curiosity, creativity, and the desire to build something meaningful together.\n\n" +
                "The submission date, December 28th, also coincides with my birthday, which makes this project even more special to me. " +
                "Being able to reach this date having created something side by side with my son is already a reward on its own.\n\n" +
                "Development & Game Jam\n\n" +
                "This game was developed for the Tiny Game Jam (12/25). " +
                "We started the project on December 26th, beginning with brainstorming the core idea and creating the first visual concepts.\n\n" +
                "The main goal was to keep the scope small and focused, while experimenting with storytelling through visual interpretation and context — " +
                "fitting the spirit of a short game jam.\n\n" +
                "Technical & Creative Notes\n\n" +
                "Engine: Unity\n\n" +
                "Assets: Some sprites and sounds were sourced from copyright-free resources.\n\n" +
                "Art: Not all images were generated by AI — several drawings and ideas came directly from my son.\n\n" +
                "AI Tools: We also used AI tools such as Gemini (Nano Banana) and ChatGPT, mainly to:\n\n" +
                "- Help translate the story and texts into English\n" +
                "- Assist with image concepts and refinement\n" +
                "- Improve clarity and consistency of written content\n\n" +
                "AI was used as a supporting tool, not as a replacement for creativity. " +
                "The project combines human ideas, learning, experimentation, and play.";
        }
    }   
    
    public void UpdateLanguageMarkers()
    {
        // Cria o LanguageManager se não existir
        if (LanguageManager.Instance == null)
        {
            GameObject lmObject = new GameObject("LanguageManager");
            lmObject.AddComponent<LanguageManager>();
        }
        
        string currentLanguage = LanguageManager.Instance.currentLanguage;
        
        // Mostra o marcador do idioma selecionado
        if (currentLanguage == "pt")
        {
            if (markPt != null) markPt.SetActive(true);
            if (markEn != null) markEn.SetActive(false);
        }
        else // en ou qualquer outro
        {
            if (markPt != null) markPt.SetActive(false);
            if (markEn != null) markEn.SetActive(true);
        }
    }

    public void OnClickAbout()
    {
        panelStart.SetActive(false);
        panelAbout.SetActive(true);
    }

    public void OnClickStart()
    {
        SceneManager.LoadScene("History");
    }

    public void OnClickExitAbout()
    {
        panelStart.SetActive(true);
        panelAbout.SetActive(false);
    }


    public void OnClickExit()
    {
        Application.Quit();
    }

    public void SetPortugueseLanguage()
    {
        Debug.Log("Idioma definido para Português (pt-BR)");
        
        // Cria o LanguageManager se não existir
        if (LanguageManager.Instance == null)
        {
            GameObject lmObject = new GameObject("LanguageManager");
            lmObject.AddComponent<LanguageManager>();
        }
        
        // Define português como idioma
        LanguageManager.Instance.SetLanguage("pt");
        
        // Atualiza o texto do About imediatamente
        UpdateAboutText();
        
        // Atualiza os marcadores de idioma
        UpdateLanguageMarkers();
        
        // Se o GameManager já existe, força o reload dos dados
        if (GameManager.Instance != null)
        {
            GameManager.Instance.LoadGameDataFromLanguage();
            Debug.Log("GameManager recarregado com dados em Português");
        }
    }
    
    public void SetEnglishLanguage()
    {
        // Cria o LanguageManager se não existir
        if (LanguageManager.Instance == null)
        {
            GameObject lmObject = new GameObject("LanguageManager");
            lmObject.AddComponent<LanguageManager>();
        }
        
        // Define inglês como idioma
        LanguageManager.Instance.SetLanguage("en");
        
        // Atualiza o texto do About imediatamente
        UpdateAboutText();
        
        // Atualiza os marcadores de idioma
        UpdateLanguageMarkers();
        
        // Se o GameManager já existe, força o reload dos dados
        if (GameManager.Instance != null)
        {
            GameManager.Instance.LoadGameDataFromLanguage();
            Debug.Log("GameManager recarregado com dados em English");
        }
    }

}
